name: cd
on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install Dependencies
        run: npm ci
      
      - name: Build Packages
        run: npm run build

      - name: Run Test Coverage
        run: npm run test:cover -- --ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release